
        save(ww,file="Data/DataForFigures/ww.Rds")
            save(pft_sum_poly_rob4_orc,file="Data/DataForFigures/pft_sum_poly_rob4_orc.Rds")
            save(cveg_sum_poly_rob4_orc,file="Data/DataForFigures/cveg_sum_poly_rob4_orc.Rds")
        #save(PFTs11_horizons3,file="Data/DataForFigures/PFTs11_horizons3.Rds")
        #save(PFT_change,"Data/DataForFigures/PFT_change.Rds")
        #save(PFTs11_horizons3_orc,file="Data/DataForFigures/PFTs11_horizons3_orc.Rds")
        save(PFT_change_orc,file="Data/DataForFigures/PFT_change_orc.Rds")
        save(PFTs11_horizons3_car,file="Data/DataForFigures/PFTs11_horizons3_car.Rds")
        save(PFT_change_car,file="Data/DataForFigures/PFT_change_car.Rds")
            save(elas_data,file="Data/DataForFigures/elas_data.Rds")
                save(pft_es_lpj,file="Data/DataForFigures/pft_es_lpj.Rds")
                save(pft_es_car,file="Data/DataForFigures/pft_es_car.Rds")                
                save(pft_es_orc,file="Data/DataForFigures/pft_es_orc.Rds")
                    save(ES_val_lpj5,file="Data/DataForFigures/ES_val_lpj5.Rds")
                    save(ES_val_lpj6,file="Data/DataForFigures/ES_val_lpj6.Rds")
                    #save(ES_val_car5,file="Data/DataForFigures/ES_val_car5.Rds")    
                    #save(ES_val_car6,file="Data/DataForFigures/ES_val_car6.Rds")  
                    save(ES_val_orc5,file="Data/DataForFigures/ES_val_orc5.Rds")
                    save(ES_val_orc6,file="Data/DataForFigures/ES_val_orc6.Rds")
            save(map_coef,file="Data/DataForFigures/map_coef.Rds")
      